# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 234aaf8b1a19b69b31b2cad1b7d549d40d714d1e5c6e7409169818fc71c6a1b7505555a0349b7f43b6a155f26790caaa90a67c4b6864f816291d470e5feb99ef

test:
  secret_key_base: b0941b420f136967057cfe06add8a9b80c492b21eb0a6962537c5bc23037e1a6a3065561e98633f87de6f9159f73d131ce238204a84a0d6619d27644521314b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
